name: C++ CI Workflow with conda-forge dependencies

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build:
    name: '[${{ matrix.shell }}@${{ matrix.os }}@pin:${{ matrix.pinocchio_version }}@urdf:${{ matrix.urdfdom_version }}@py:${{ matrix.python_version }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest]
        pinocchio_version: [3.4.0]
        urdfdom_version: [4.0.1=*_0, 4.0.1=*_1]
        python_version: [3.11]
        shell: ["zsh", "bash"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4


    - name: Install zsh [linux]
      if: contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        sudo apt-get install zsh

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest

    - name: Init conda for zsh [zsh]
      if: contains(matrix.shell, 'zsh')
      shell: zsh -l {0}
      run: |
        conda init zsh
        conda env list

    - name: Init conda env [zsh]
      if: contains(matrix.shell, 'zsh')
      shell: zsh -l {0}
      run: |
        conda create -n debug-pinocchio
        conda activate debug-pinocchio
        conda install pinocchio=${{ matrix.pinocchio_version }} urdfdom=${{ matrix.urdfdom_version }} python=${{ matrix.python_version }}
        conda list

    - name: Init conda env [bash]
      if: contains(matrix.shell, 'bash')
      shell: bash -l {0}
      run: |
        conda create -n debug-pinocchio
        conda activate debug-pinocchio
        conda install pinocchio=${{ matrix.pinocchio_version }} urdfdom=${{ matrix.urdfdom_version }} python=${{ matrix.python_version }}
        conda list

    - name: Run test [bash]
      if: contains(matrix.shell, 'bash')
      shell: bash -l {0}
      run: |
        conda activate debug-pinocchio
        python3 -c  "import pinocchio; print(pinocchio.__version__)"

    - name: Run test [zsh]
      if: contains(matrix.shell, 'zsh')
      shell: zsh -l {0}
      run: |
        conda activate debug-pinocchio
        python3 -c  "import pinocchio; print(pinocchio.__version__)"
