name: C++ CI Workflow with conda-forge dependencies

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build:
    name: '[${{ matrix.os }}@pin:${{ matrix.pinocchio_version }}@urdf:${{ matrix.urdfdom_version }}@py:${{ matrix.python_version }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
        pinocchio_version: [3.3.0, 3.3.1, 3.4.0]
        urdfdom_version: [4.0.1=*_0, 4.0.1=*_1]
        python_version: ["3.10", 3.11, 3.12, 3.13]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: .github/workflows/ci_env.yml

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        micromamba install pinocchio=${{ matrix.pinocchio_version }} urdfdom=${{ matrix.urdfdom_version }} python=${{ matrix.python_version }}
        micromamba list

    - name: Run test
      shell: bash -l {0}
      run: |
        python3 -c  "import pinocchio; print(pinocchio.__version__)"
